parameters:
  json_list.class: "AdminBundle\\Service\\DataTables\\JsonList"
  admin_manager.class: "AdminBundle\\Service\\AdminManager"
  upload_handler.class: "AdminBundle\\Service\\UploadHandler"


services:
    json_list:
        class: %json_list.class%
        arguments:
          - "@request_stack"
        scope: request_stack
        
    admin_manager:
        class: %admin_manager.class%
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@security.token_storage"
          - { parameters: %core% }
          - "@service_container"
            
    upload_handler:
        class: %upload_handler.class%
        arguments:
            - %kernel.root_dir%
            - "@router"
            - "@request_stack"
            - "@doctrine.orm.entity_manager"
        scope: request
        
    google.api.client:
        class: "AdminBundle\\Service\\GoogleClient"
        arguments: ["%google_analytics.application_name%", "%google_analytics.oauth2_client_id%", "%google_analytics.oauth2_client_secret%", "%google_analytics.oauth2_redirect_uri%", "%google_analytics.developer_key%"]

    google.api.analytics:
        class: "AdminBundle\\Service\\AnalyticsService"
        arguments: ["@google.api.client", "@doctrine"]
    
    google.api.youtube:
        class: "AdminBundle\\Service\\YoutubeService"
        arguments: ["@google.api.client"]